[connections.postgresql]
dialect = "postgresql"
url = "postgresql://neondb_owner:npg_Zhrwj97yOMTK@ep-super-river-ac6v9h6n-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"